# Generated by Django 5.1.5 on 2025-01-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedsecret',
            name='encryption_key',
            field=models.TextField(default='default_key'),
            preserve_default=False,
        ),
    ]
